
services:
  database:
    ports:
      - "5432:5432"
    depends_on:
      - pgadmin

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:5050"
    volumes:
      - type: bind
        source: ./pgadmin_servers.json
        target: /pgadmin4/servers.json
    environment:
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: qwerty12

  traefik:
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:$SERVER_PORT"
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
      - "8080:8080"
