version: "3.9"

services:

  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      # debug info
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      #
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      # debug info
      - "8080:8080"
      #
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
