
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/leaders_app
    username: user
    password: qwerty12

  jpa:
    hibernate:
      ddl-auto: validate

  error:
    include-message: always

leaders_backend:
  graph_hopper_token: 03f13d82-1328-449a-b6ec-7d547ee548c0
